### PR TITLE
Improve native performance by using the template element

### PR DESCRIPTION
**Pull request by TimvdLippe**
Per https://twitter.com/TimvdLippe/status/965322789942169602 `template` is a lot faster and dynamically creating DOM. CC @robdodson

P.S. There are no instructions in the repository on how to reproduce the benchmark results you posted in https://twitter.com/julienrenaux/status/965168453748428800 Could you add these instructions to the README? When I run LightHouse on this branch, I get a 99 performance score with "First Meaningful Paint" of 1340ms.

### CODE REVIEW

**Comment by shprink** [comment]
thank you. Will upload the lighthouse tests ASAP. Since they are ran locally, you will get different results than mine for sure. The gaps between implementations are important, not the actual numbers.

**Comment by shprink** [comment]
```

const lighthouse = require('lighthouse');
const chromeLauncher = require('chrome-launcher');
const _find = require('lodash/find');
const _set = require('lodash/set');

const config = {
    "extends": "lighthouse:default",
    "settings": {
        "onlyCategories": ["performance"]
    },
    "categories": {
        "performance": {
            "weight": 1
        }
    }
};

function launchChromeAndRunLighthouse(url, flags = {}, config = null) {
    return chromeLauncher.launch(flags).then(chrome => {
        flags.port = chrome.port;
        return lighthouse(url, flags, config).then(results =>
            chrome.kill().then(() => results));
    });
}

const flags = {
    chromeFlags: ['--headless']
};

const endpoints = ['native', 'stencil', 'polymer2', 'angular-elements', 'vue'];
const results = {};
const tryNumber = 5;

let promises = Promise.resolve();
for (let i = 0; i < endpoints.length; i++) {
    const endpoint = endpoints[i];
    _set(results, `[${endpoint}].performance`, []);
    _set(results, `[${endpoint}].fmp`, []);

    for (let j = 0; j < tryNumber; j++) {
        promises = promises.then(() => {
            console.log(`running: https://wc-todo.firebaseapp.com/${endpoint}`);
            return launchChromeAndRunLighthouse(`https://wc-todo.firebaseapp.com/${endpoint}`, flags, config);
        }).then(r => {
            const perf = r.reportCategories[0].score;
            const fmp = _find(r.reportCategories[0].audits, { "id": "first-meaningful-paint" }).result.rawValue;
            console.log(perf, fmp)
            results[endpoint].performance.push(perf);
            results[endpoint].fmp.push(fmp);
        });
    }
};
promises.then(() => {
    Object.keys(results).forEach(endpoint => {
        const { performance, fmp } = results[endpoint];
        const perf = Math.round(performance.reduce((previous, current) => {
            return previous + current;
        }, 0) / tryNumber);
        const firstMeaningfull = Math.round(fmp.reduce((previous, current) => {
            return previous + current;
        }, 0) / tryNumber);
        console.log(`-----${endpoint}-----`)
        console.log('performance note', perf)
        console.log('first-meaningful-paint', firstMeaningfull + ' ms')
    });
})
```

**Comment by robdodson** [comment]
thank you for doing this @TimvdLippe, you rock!!!

**Comment by shprink** [comment]
I deployed, does not change anything. One thing that could potentially help the first meaning full paint though is to optimize the render method of `my-todo` https://github.com/shprink/web-components-todo/blob/master/native/js/my-todo.js#L50-L64

So far native is less fast than Skate, Polymer and Stencil:

image

Do you think you can get a crack at it @TimvdLippe ? 

thanks very much

**Comment by TimvdLippe** [comment]
@shprink I think the benchmark is skewed, as other factors are more likely at play. For example view-source:https://wc-todo.firebaseapp.com/stencil/ shows that Stencil only loads 1 build file while native has 3 roundtrips to the 3 different files. If you would like to have comparable results, I think you have to eliminate these discrepancies. It is strictly impossible to have a faster response with an abstraction rather than the written out and optimized native version.

For example, you can easily pre-render with native web components. However, with native you pay an extra cost of shipping the extra HTML bytes, which is not included in First Meaningful Paint, but is in full load. To improve this benchmark, factors such as number of network roundtrips, all pre-rendering or none and an efficient implementation either with functional + vdom or imperative without vdom should be standardized between all implementations.

**Comment by shprink** [comment]
The goal of this repo is to show what you get out of the box. "As a new WC developer, with what technology do I get the most benefit out of the box?", "what WC syntax I am the most confortable using?" that's the kind of questions this repo is trying to answer. 

I do not see the point comparing:

> "an efficient implementation either with functional + vdom or imperative without vdom should be standardized between all implementations."

At the end they all export WC, the results would be similar.

I am going to bundle the 3 components together you are right on this.

**Comment by shprink** [comment]
Better results when bundled:

image

**Pull request merged**
