### PR TITLE
Adds svelte example

### PR DESCRIPTION
**Pull request by eddyloewen**
Hi,

I think [svelte](https://svelte.technology/) looks really promising and I got it to build and render native custom elements.

It would be really nice if you @shprink could deploy this along with the others and also run the benchmark and share it one more time?

Thank you very much in advance

### CODE REVIEW

**Comment by shprink** [comment]
Great stuff, will play with it and deploy asap

**Comment by eddyloewen** [comment]
Thanks! I just found a "little" bug that I introduced. In the root package.json, when running the build:svelte script it needs to move the /public directory rather then /dist. Should I open another PR? Or will you fix that yourself?

**Comment by shprink** [comment]
Hello,

when I run `npm run build && npm start` under `./svelte` I get the following error:

image

**Comment by eddyloewen** [comment]
Hey,

I know... I found this as well after you merged the PR. It's because the rollup config is configured to transpile and uglify the bundle when not running in watch mode.

If you disable transpilation + uglify it should work. Unfortunately there seems to be an issue when trying to minify the bundle . I couldn't find a solution by now. I'm still trying to figure that out.

**Comment by shprink** [comment]
Deployed: https://wc-todo.firebaseapp.com/svelte/

if you find a fix, base your fix on master.

thanks

**Comment by oskarrough** [comment]
That error comes when you try to transpile a custom element class with babel. See https://github.com/github/babel-plugin-transform-custom-element-classes#problem

**Pull request merged**
